# Generated by Django 4.1.3 on 2022-12-10 00:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ski',
            name='image',
            field=models.ImageField(default=False, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ski',
            name='color_tag',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None),
        ),
    ]
