# Generated by Django 4.1.3 on 2022-11-21 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ski_number', models.CharField(max_length=64)),
                ('technique', models.CharField(max_length=64)),
                ('grind', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=64)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('url_img', models.URLField()),
                ('color_tag', models.IntegerField()),
                ('notes', models.CharField(max_length=256)),
                ('ski_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ski', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testski', to='skis.ski')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=64)),
                ('ski', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ski', to='skis.ski')),
            ],
        ),
        migrations.CreateModel(
            name='Skitest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_test', models.DateField(auto_now_add=True)),
                ('temprature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('location', models.CharField(max_length=64)),
                ('snow_type', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=256)),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester', to=settings.AUTH_USER_MODEL)),
                ('testski', models.ManyToManyField(to='skis.testski')),
            ],
        ),
    ]
