# Generated by Django 4.1.3 on 2022-11-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skis', '0002_ski_testski_technique_skitest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='ski',
        ),
        migrations.AlterField(
            model_name='skitest',
            name='date_of_test',
            field=models.DateField(),
        ),
    ]
